  const  {
  DB_HOST,
  DB_USER,
  DB_USER_PASSWORD,
  DB_DOCKER_PORT,
  DB_LOCAL_PORT,
  DB_NAME,
  POOL_CONNECTION_LIMIT,
  POOL_QUEUE_LIMIT,
  NODE_ENV,
  APP_LOCAL_PORT,
  APP_DOCKER_PORT,
  FRONT_END_URL,
  RAW_ALLOWED_IPS
 } = process.env;

 const IS_DEV_ENV = NODE_ENV === 'development';

export const env = {
  DB_HOST,
  DB_USER,
  DB_USER_PASSWORD,
  DB_DOCKER_PORT,
  DB_PORT: Number.parseInt( IS_DEV_ENV ? DB_LOCAL_PORT : DB_DOCKER_PORT),
  PORT: IS_DEV_ENV ? APP_LOCAL_PORT : APP_DOCKER_PORT,
  DB_NAME,
  POOL_CONNECTION_LIMIT: Number.parseInt(POOL_CONNECTION_LIMIT),
  POOL_QUEUE_LIMIT: Number.parseInt(POOL_QUEUE_LIMIT),
  NODE_ENV,
  FRONT_END_URL,
  ALLOWED_IPS: RAW_ALLOWED_IPS?.split(' ') || []
 }